name: Build and Deploy Sagittarius FAQ

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build static site
        run: npm run generate

      - name: Create archive
        run: |
          cd .output/public
          tar -czf ../../site.tar.gz .
          cd ../..

      - name: Prepare server directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            # Ensure directory exists
            mkdir -p /home/fadeusz/containers/pomoc.kssagittarius.pl/public
            
            # Stop container
            cd /home/fadeusz/containers/pomoc.kssagittarius.pl
            docker-compose down || true

      - name: Deploy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: "site.tar.gz,docker-compose.yml,Caddyfile"
          target: "/home/fadeusz/containers/pomoc.kssagittarius.pl/"
          overwrite: true

      - name: Extract files and start container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /home/fadeusz/containers/pomoc.kssagittarius.pl
            
            # Clean public directory
            rm -rf public/*
            
            # Extract new files
            tar -xzf site.tar.gz -C public/
            
            # Remove archive
            rm -f site.tar.gz
            
            # Set proper permissions
            chmod -R 755 public/
            
            # Start container
            docker-compose up -d
            
            # Clean up old images
            docker image prune -f
            
            echo "Deployment completed successfully!"
