name: Build and Deploy Sagittarius FAQ

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build static site
        run: npm run generate

      - name: Create archive
        run: |
          cd .output/public
          tar -czf ../../site.tar.gz .
          cd ../..

      - name: Clean target directory on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            # Ensure directory exists
            mkdir -p /var/www/domains/pomoc.kssagittarius.pl/public
            
            # Clean current public directory
            rm -rf /var/www/domains/pomoc.kssagittarius.pl/public/*

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: "site.tar.gz"
          target: "/var/www/domains/pomoc.kssagittarius.pl/"
          overwrite: true

      - name: Extract files and set permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/domains/pomoc.kssagittarius.pl
            
            # Extract archive
            tar -xzf site.tar.gz -C public/
            
            # Remove archive
            rm -f site.tar.gz
            
            # Set proper permissions
            find public/ -type d -exec chmod 755 {} \;
            find public/ -type f -exec chmod 644 {} \;
            
            # Set ownership (adjust user:group as needed)
            # chown -R www-data:www-data public/ || true
            
            echo "Deployment completed successfully!"
